### ISSUE TITLE
Two cell finder plugins in napari?

### ISSUE THREAD

**Issue by psobolewskiPhD** [brainglobe/cellfinder-napari#36]
This is confusing:
<img width="1192" alt="image" src="https://user-images.githubusercontent.com/76622105/151662297-b8fb3781-c6e3-499e-95ed-1c59c204e9b7.png">
I guess the bottom one (napari-cellfinder) is archived, so the top one is the real one.
Is there a way to flag/change that? Or is this the desired behavior with 2 plugins.

**Comment by adamltyson** [comment]
That is confusing. The old one (napari-cellfinder) [is blocked from appearing on the napari hub](https://github.com/chanzuckerberg/napari-hub/issues/38), but it still shows up in the GUI.

I had kept it around because it was being used for old projects, but I've removed it from PyPI now (along with `napari-brainreg`). Not sure how long changes takes to propagate through, but it should be gone now.

Thanks for spotting @psobolewskiPhD!
