### ISSUE TITLE
Create sensible issue/PR templates

### ISSUE THREAD

**Issue by alessandrofelder** [brainglobe/cellfinder-napari#40]
if we can come up with something sensible.

**Comment by dstansby** [comment]
Instead of doing this for every repository, we should set it up across the brainglobe org by creating a new `.github` repository, as explained here: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file

For writing templates, https://github.com/stevemao/github-issue-templates/ seems to be a well used resource for template templates (😆), so we could probably pick ones from there and customise as needed.

**Comment by adamltyson** [comment]
Added in https://github.com/brainglobe/.github/pull/4
